runtime: python37

handlers:
- url: /
  script: auto

- url: /cloud_masks/(.*\.(gif|jpg))
  script: auto

- url: /favicon.ico
  static_files: favicon.png
  upload: favicon.png

- url: /(.*\.(css|js|png|gif|jpg|xml|svg|xml))$
  static_files: contents/\1
  upload: .*\.(css|js|png|gif|jpg|xml|svg|xml)$
